/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-1",
    "aws_cognito_identity_pool_id": "ap-southeast-1:d1f1e7d7-1177-4c7c-93fb-2a86559c4b48",
    "aws_cognito_region": "ap-southeast-1",
    "aws_user_pools_id": "ap-southeast-1_xgXKSaYkF",
    "aws_user_pools_web_client_id": "1omubbsfatornbebrdgdcgpbml",
    "oauth": {}
};


export default awsmobile;
